services:
  # A Docker web service
  - type: web
    name: segmentation
    runtime: python:3.8.5
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT